mysite/feed/urls.py
from . import views
from django.urls import path

app_name = 'feed'
urlpatterns = [
    path('', views.index, name="index"),
    path('feed/', views.feed, name="feed"),
    path('post/<int:post_id>', views.postDetail, name="postDetail"),
    path('createPost/', views.CreatePost.as_view(), name="createPost"),
    path('updatePost/<int:post_id>', views.updatePost, name="updatePost"),
    path('deletePost/<int:post_id>', views.deletePost, name="deletePost"),
    path('comment/<int:comment_id>', views.commentDetail, name="commentDetail"),
    path('createComment/', views.CreateComment.as_view(), name="createComment"),
    path('createComment/<int:comment_id>', views.CreateComment.as_view(), name="createChildComment"),
    path('updateComment/<int:comment_id>', views.updateComment, name="updateComment"),
    path('deleteComment/<int:comment_id>', views.deleteComment, name="deleteComment"),
    path('savePost/<int:post_id>', views.savePost, name="savePost"),
    path('unsavePost/<int:post_id>', views.unsavePost, name="unsavePost"),
    path('likePost/<int:post_id>', views.likePost, name="likePost"),
    path('unlikePost/<int:post_id>', views.unlikePost, name="unlikePost"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import feed.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feed.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/user/urls.py
from . import views
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', authentication_views.LoginView.as_view(template_name='user/login.html'), name="login"),
    path('logout/', authentication_views.LogoutView.as_view(template_name='user/logout.html'), name="logout"),
    path('profile/<username>', views.profilepage, name="profile"),
    path('editProfile/<username>', views.editProfile, name="editProfile"),
    path('followProfile/<profile_id>', views.followProfile, name="followProfile"),
    path('unfollowProfile/<profile_id>', views.unfollowProfile, name="unfollowProfile"),
    path('deleteUser/<username>', views.deleteUser, name="deleteUser"),
    path('savedPosts/<username>', views.savedPosts, name="savedPosts"),
    path('likedPosts/<username>', views.likedPosts, name="likedPosts"),
    path('followingPosts/<username>', views.followingPosts, name="followingPosts"),
    path('followers/<username>', views.followers, name="followers"),
]

mysite/feed/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    def __str__(self):
        if len(self.content) > 50:
            return self.user.username + " -> " + self.title + ": " + self.content[0:50] + "..."
        else:
            return self.user.username + " -> " + self.title + ": " + self.content[0:50]

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=2000)
    image = models.ImageField(default='postpic.jpg', upload_to='post_pictures')
    datetime = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField('user.Profile')

class Comment(models.Model):
    def __str__(self):
        return self.user.username + ": '" + self.title + "' on '" + self.post.title + "'"

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=1)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=500)
    datetime = models.DateTimeField(auto_now_add=True)

mysite/feed/forms.py
from django import forms
from .models import Post, Comment

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'content']

mysite/feed/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import CreatePostForm, CreateCommentForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.db.models import Q
from user.models import Profile, User

# Create your views here.
def index(request):
    return render(request, 'feed/index.html', {})

@login_required
def feed(request):
    post_list = Post.objects.all().order_by('-datetime')

    post_search = request.GET.get('post_content')
    if post_search != '' and post_search is not None:
        post_list = post_list.filter(Q(title__icontains=post_search) | Q(content__icontains=post_search))
    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)

    return render(request, 'feed/feed.html', {'post_list': post_list})

@login_required
def postDetail(request, post_id):
    post = Post.objects.get(pk=post_id)
    comment_list = Comment.objects.filter(post=post, parent__isnull=True).order_by('-id')
    return render(request, 'feed/postDetail.html', {'post': post, 'comment_list': comment_list})

@login_required
def createPost(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'feed/feed.html', {})
    else:
        form = CreatePostForm()

    return render(request, 'feed/createPost.html', {'form': form})

class CreatePost(CreateView):
    model = Post
    fields = ['title', 'content', 'image']
    template_name = 'feed/createPost.html'
    success_url = reverse_lazy('feed:feed')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

@login_required
def updatePost(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CreatePostForm(request.POST or None, request.FILES or None, instance=post)

    if form.is_valid():
        form.save()
        return redirect(request.GET.get('next'))

    return render(request, 'feed/createPost.html', {'form': form, 'post': post})

@login_required
def deletePost(request, post_id):
    post = Post.objects.get(id=post_id)

    if request.method == 'POST':
        post.delete()
        return redirect('feed:feed')

    return render(request, 'feed/deletePost.html', {'post': post})

@login_required
def commentDetail(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    comment_list = Comment.objects.filter(parent=comment).order_by('-id')

    return render(request, 'feed/commentDetail.html', {'comment': comment, 'comment_list': comment_list})

@login_required
def createComment(request):
    if request.method == 'POST':
        form = CreateCommentForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'feed/feed.html', {})
    else:
        form = CreateCommentForm()

    return render(request, 'feed/createComment.html', {'form': form})

class CreateComment(CreateView):
    model = Comment
    fields = ['title', 'content']
    template_name = 'feed/createComment.html'
    success_url = reverse_lazy('feed:feed')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = Post.objects.get(id=int(self.request.GET.get('post_id')))
        if self.request.GET.get('comment_id'):
            form.instance.parent = Comment.objects.get(id=int(self.request.GET.get('comment_id')))
        return super().form_valid(form)

@login_required
def updateComment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    form = CreateCommentForm(request.POST or None, instance=comment)

    if form.is_valid():
        form.save()
        return redirect(request.GET.get('next'))

    return render(request, 'feed/createComment.html', {'form': form, 'comment': comment})

@login_required
def deleteComment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)

    if request.method == 'POST':
        comment.delete()
        return redirect(request.GET.get('next'))

    return render(request, 'feed/deleteComment.html', {'comment': comment})

@login_required
def savePost(request, post_id):
    post = Post.objects.get(id=post_id)
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        profile.savedPosts.add(post)
        return redirect(request.GET.get('next'))

    return render(request, 'feed/savePost.html', {'post': post, 'profile': profile})

@login_required
def unsavePost(request, post_id):
    post = Post.objects.get(id=post_id)
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        profile.savedPosts.remove(post)
        return redirect(request.GET.get('next'))

    return render(request, 'feed/unsavePost.html', {'post': post, 'profile': profile})

@login_required
def likePost(request, post_id):
    post = Post.objects.get(id=post_id)
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        post.likes.add(profile)
        profile.likedPosts.add(post)
        return redirect(request.GET.get('next'))

    return render(request, 'feed/likePost.html', {'post': post, 'profile': profile})

@login_required
def unlikePost(request, post_id):
    post = Post.objects.get(id=post_id)
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        post.likes.remove(profile)
        profile.likedPosts.remove(post)
        return redirect(request.GET.get('next'))

    return render(request, 'feed/unlikePost.html', {'post': post, 'profile': profile})

mysite/feed/templates/feed/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <title>Feed</title>
        <link rel="stylesheet" href="{% static 'feed/style.css' %}" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark fixed-top">
            <a href="{% url 'feed:feed' %}" class="navbar-brand">Social Media App</a>
            <div class="navbar">
                {% if user.is_authenticated %}
                    <a href="{% url 'feed:createPost' %}" class="nav-item nav-link">
                        <img src="../../../pictures/plus.png" width="30px">
                    </a>
                    <a href="{% url 'feed:feed' %}" class="nav-item nav-link">
                        <img src="../../../pictures/home.png" width="30px">
                    </a>
                    <a href="{% url 'user:logout' %}" class="nav-item nav-link">
                        <img src="../../../pictures/logout.png" width="30px">
                    </a>
                    <a href="{% url 'user:profile' request.user.username %}" class="nav-item nav-link">
                        <img src="{{ user.profile.image.url }}" width="50px" height="50px">
                    </a>
                {% else %}
                    <a href="{% url 'user:login' %}" class="nav-item nav-link">Login</a>
                    <a href="{% url 'user:register' %}" class="nav-item nav-link">Register</a>
                {% endif %}
            </div>
        </nav>
        <br><br><br><br>
        {% block body %}
        {% endblock %}
        <footer class="bg-dark text-center text-white fixed-bottom">
            <div class="text-center p-3">
                &copy; 2023 Nicholas Stephenson
            </div>
        </footer>
        <br><br>
    </body>
</html>

mysite/feed/templates/feed/commentDetail.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-3 offset-md-1">
            <img src="{{ comment.post.image.url }}" class="card" width="100%">
        </div>
        <div class="col-md-6">
            <h1>
                <i>{{ comment.post.title }}</i>
            </h1>
            <a href="{% url 'user:profile' comment.post.user.username %}">
                <div class="col-md-4">
                    <div class="row">
                        <img src="{{ comment.post.user.profile.image.url }}" width="30px" style="margin-right:5px;" />
                        <h6>{{ comment.post.user.username }}</h6>
                    </div>
                </div>
            </a>
            <div class="row">
                <div class="col-md-4">
                    {% load tz %}
                    {% timezone request.user.profile.timezone %}
                    <h6>
                        <i>{{ comment.post.datetime }}</i>
                    </h6>
                    {% endtimezone %}
                </div>
            </div>
            <h2>
                <i>{{ comment.post.content|truncatewords_html:20 }}</i>
            </h2>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-1">
            <input type="button" value="<" onClick="javascript:history.go(-1);" style="margin-left: 22px; background-color: Transparent; border: none;">
            <a href="{% url 'feed:postDetail' comment.post.id %}" class="btn">^</a>
        </div>
        <div class="col-md-10">
            <h2>
                <b>{{ comment.title }}</b>
            </h2>
            <h4>
                <b>{{ comment.content }}</b>
            </h4>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-11 offset-md-1">
            <h3>Replies:</h3>
        </div>
    </div>
    {% for subComment in comment_list %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2>{{ subComment.title }}</h2>
                <a href="{% url 'user:profile' subComment.user.username %}">
                    <div class="col-md-4">
                        <div class="row">
                            <img src="{{ subComment.user.profile.image.url }}" height="30px" style="margin-right:5px;" />
                            <h6>{{ subComment.user.username }}</h6>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 offset-md-2">
                {% load tz %}
                {% timezone request.user.profile.timezone %}
                <h6>{{ comment.datetime }}</h6>
                {% endtimezone %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 offset-md-2">
                <h4>{{ subComment.content }}</h4>
            </div>
            <div class="col-md-3 offset-md-1">
                <a href="{% url 'feed:createComment' %}?comment_id={{ subComment.id }}&post_id={{ comment.post.id }}&next={{ request.path }}" class="btn btn-success">Reply</a>
                <a href="{% url 'feed:commentDetail' subComment.id %}" class='btn btn-info'>See Replies</a>
                {% if subComment.user == request.user %}
                    <a href="{% url 'feed:updateComment' subComment.id %}?next={{ request.path }}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'feed:deleteComment' subComment.id %}?next={{ request.path }}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>
        <hr>
    {% endfor %}
    <div class="row">
        <div class="col-md-2 offset-md-5">
            <a href="{% url 'feed:createComment' %}?comment_id={{ comment.id }}&post_id={{ comment.post.id }}&next={{ request.path }}" class="btn btn-info">Add Reply</a>
        </div>
    </div>
    <br>
{% endblock %}

mysite/feed/templates/feed/createComment.html
{% extends 'feed/base.html' %}

{% block body %}
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        Comment Content
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name|title }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn-info">Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/feed/templates/feed/createPost.html
{% extends 'feed/base.html' %}

{% block body %}
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        Post Content
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name|title }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn-info">Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/feed/templates/feed/deleteComment.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-2">
            <form method="POST">
                {% csrf_token %}
                <h2>Are you sure you want to delete '{{ comment.title }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

mysite/feed/templates/feed/deletePost.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-2">
            <form method="POST">
                {% csrf_token %}
                <h2>Are you sure you want to delete '{{ post.title }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

mysite/feed/templates/feed/feed.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-8 offset-md-1">
            <h1>My Feed:</h1>
        </div>
        <div class="col-md-3">
            <form action="" method="GET">
                <input type="search" name="post_content" value="{{ request.GET.post_content }}">
                <button type="submit" class="btn btn-secondary btn-sm">Search</button>
            </form>
            <div class="offset-md-2">
                <a href="{% url 'feed:feed' %}" class="btn btn-secondary btn-sm">Clear Search</a>
            </div>
        </div>
    </div>
    {% for post in post_list %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <a href="{% url 'feed:postDetail' post.id %}">
                    <h2>{{ post.title }}</h2>
                </a>
                <a href="{% url 'user:profile' post.user.username %}">
                    <div class="col-md-4">
                        <div class="row">
                            <img src="{{ post.user.profile.image.url }}" height="30px" style="margin-right:5px;" />
                            <h6>{{ post.user.username }}</h6>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2">
                <a href="{% url 'feed:postDetail' post.id %}">
                    <img class="card" width="200px" src="{{ post.image.url }}" />
                </a>
            </div>
            <div class="col-md-4">
                <h4>{{ post.content|truncatewords_html:50 }}</h4>
            </div>
            <div class="col-md-3 offset-md-1">
                <a href="{% url 'feed:postDetail' post.id %}" class="btn btn-primary">Expand</a>
                {% if request.user.profile not in post.likes.all %}
                    <a href="{% url 'feed:likePost' post.id %}?next={{ request.path }}" class="btn btn-success btn-sm">Like Post</a>
                {% endif %}
                {% if request.user.profile in post.likes.all %}
                    <a href="{% url 'feed:unlikePost' post.id %}?next={{ request.path }}" class="btn btn-secondary btn-sm">Unlike Post</a>
                {% endif %}
                {% if post not in request.user.profile.savedPosts.all  %}
                    <a href="{% url 'feed:savePost' post.id %}?next={{ request.path }}" class="btn btn-info btn-sm">Save Post</a>
                {% endif %}
                {% if post in request.user.profile.savedPosts.all %}
                    <a href="{% url 'feed:unsavePost' post.id %}?next={{ request.path }}" class="btn btn-secondary btn-sm">Unsave Post</a>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 offset-md-2">
                {% load tz %}
                {% timezone request.user.profile.timezone %}
                <h6>{{ post.datetime }}</h6>
                {% endtimezone %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2">
                <h6>Likes: {{ post.likes.count }}</h6>
            </div>
        </div>
        <hr>
    {% endfor %}
    <div class="row">
        <div class="col-md-4 offset-md-5">
            {% if post_list.has_previous %}
                <a href="?page=1{% if request.GET.post_content is not None %}&post_content={{ request.GET.post_content }}{% endif %}" class="btn btn-info">First</a>
                <a href="?page={{ post_list.previous_page_number }}{% if request.GET.post_content is not None %}&post_content={{ request.GET.post_content }}{% endif %}" class="btn btn-info">Previous</a>
            {% endif %}
            Page: {{ post_list.number }} of {{ post_list.paginator.num_pages }}
            {% if post_list.has_next %}
                <a href="?page={{ post_list.next_page_number }}{% if request.GET.post_content is not None %}&post_content={{ request.GET.post_content }}{% endif %}" class="btn btn-info">Next</a>
                <a href="?page={{ post_list.paginator.num_pages }}{% if request.GET.post_content is not None %}&post_content={{ request.GET.post_content }}{% endif %}" class="btn btn-info">Last</a>
            {% endif %}
        </div>
    </div>
    <br>
{% endblock %}

mysite/feed/templates/feed/index.html
{% extends 'feed/base.html' %}

{% block body %}
    <div class="row">
        <div class="col-md-6 offset-md-2">
            <h1>Welcome to my Social Media Site!</h1>
        </div>
    </div>
{% endblock %}

mysite/feed/templates/feed/likePost.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-5">
            <form method="POST">
                {% csrf_token %}
                <h2>Like '{{ post.title }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

mysite/feed/templates/feed/postDetail.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-1">
            <a href="{% url 'feed:feed' %}" class="btn btn-info" style="margin-left: 20px;"><</a>
        </div>
        <div class="col-md-3">
            <img src="{{ post.image.url }}" class="card" width="100%">
        </div>
        <div class="col-md-6">
            <h1>{{ post.title }}</h1>
            <a href="{% url 'user:profile' post.user.username %}">
                <div class="col-md-4">
                    <div class="row">
                        <img src="{{ post.user.profile.image.url }}" width="30px" style="margin-right:5px;" />
                        <h6>{{ post.user.username }}</h6>
                    </div>
                </div>
            </a>
            <div class="row">
                <div class="col-md-4">
                    {% load tz %}
                    {% timezone request.user.profile.timezone %}
                    <h6>{{ post.datetime }}</h6>
                    {% endtimezone %}
                </div>
            </div>
            <h2>{{ post.content }}</h2>
        </div>
        <div class="col-md-2">
            {% if request.user.profile not in post.likes.all %}
                <a href="{% url 'feed:likePost' post.id %}?next={{ request.path }}" class="btn btn-success">Like Post</a>
            {% endif %}
            {% if request.user.profile in post.likes.all %}
                <a href="{% url 'feed:unlikePost' post.id %}?next={{ request.path }}" class="btn btn-secondary">Unlike Post</a>
            {% endif %}
            {% if post not in request.user.profile.savedPosts.all  %}
                <a href="{% url 'feed:savePost' post.id %}?next={{ request.path }}" class="btn btn-info">Save Post</a>
            {% endif %}
            {% if post in request.user.profile.savedPosts.all %}
                <a href="{% url 'feed:unsavePost' post.id %}?next={{ request.path }}" class="btn btn-secondary">Unsave Post</a>
            {% endif %}
            {% if post.user == request.user %}
                <br>
                <a href="{% url 'feed:updatePost' post.id %}?next={{ request.path }}" class="btn btn-warning btn-sm" style="margin-top: 5px;">Edit</a>
                <a href="{% url 'feed:deletePost' post.id %}" class="btn btn-danger btn-sm" style="margin-top: 5px;">Delete</a>
            {% endif %}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-11 offset-md-1">
            <h2>Comments:</h2>
        </div>
    </div>
    <br>
    {% for comment in comment_list %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2>{{ comment.title }}</h2>
                <a href="{% url 'user:profile' comment.user.username %}">
                    <div class="col-md-4">
                        <div class="row">
                            <img src="{{ comment.user.profile.image.url }}" height="30px" style="margin-right:5px;" />
                            <h6>{{ comment.user.username }}</h6>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 offset-md-2">
                {% load tz %}
                {% timezone request.user.profile.timezone %}
                <h6>{{ comment.datetime }}</h6>
                {% endtimezone %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 offset-md-2">
                <h4>{{ comment.content }}</h4>
            </div>
            <div class="col-md-3 offset-md-1">
                <a href="{% url 'feed:createComment' %}?comment_id={{ comment.id }}&post_id={{ post.id }}&next={{ request.path }}" class="btn btn-success">Reply</a>
                <a href="{% url 'feed:commentDetail' comment.id %}" class='btn btn-info'>See Replies</a>
                {% if comment.user == request.user %}
                    <br>
                    <a href="{% url 'feed:updateComment' comment.id %}?next={{ request.path }}" class="btn btn-warning btn-sm" style="margin-top: 5px;">Edit</a>
                    <a href="{% url 'feed:deleteComment' comment.id %}?next={{ request.path }}" class="btn btn-danger btn-sm" style="margin-top: 5px;">Delete</a>
                {% endif %}
            </div>
        </div>
        <hr>
    {% endfor %}
    <div class="row">
        <div class="col-md-2 offset-md-5">
            <a href="{% url 'feed:createComment' %}?post_id={{ post.id }}&next={{ request.path }}" class="btn btn-info">Add Comment</a>
        </div>
    </div>
    <br>
{% endblock %}

mysite/feed/templates/feed/savePost.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-5">
            <form method="POST">
                {% csrf_token %}
                <h2>Save '{{ post.title }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

mysite/feed/templates/feed/unlikePost.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-5">
            <form method="POST">
                {% csrf_token %}
                <h2>Unlike '{{ post.title }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

mysite/feed/templates/feed/unsavePost.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-5">
            <form method="POST">
                {% csrf_token %}
                <h2>Unsave '{{ post.title }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}