mysite/feed/urls.py
from . import views
from django.urls import path

app_name = 'feed'
urlpatterns = [
    path('', views.index, name="index"),
    path('feed/', views.feed, name="feed"),
    path('post/<int:post_id>', views.postDetail, name="postDetail"),
    path('createPost/', views.CreatePost.as_view(), name="createPost"),
    path('updatePost/<int:post_id>', views.updatePost, name="updatePost"),
    path('deletePost/<int:post_id>', views.deletePost, name="deletePost"),
    path('comment/<int:comment_id>', views.commentDetail, name="commentDetail"),
    path('createComment/', views.CreateComment.as_view(), name="createComment"),
    path('createComment/<int:comment_id>', views.CreateComment.as_view(), name="createChildComment"),
    path('updateComment/<int:comment_id>', views.updateComment, name="updateComment"),
    path('deleteComment/<int:comment_id>', views.deleteComment, name="deleteComment"),
    path('savePost/<int:post_id>', views.savePost, name="savePost"),
    path('unsavePost/<int:post_id>', views.unsavePost, name="unsavePost"),
    path('likePost/<int:post_id>', views.likePost, name="likePost"),
    path('unlikePost/<int:post_id>', views.unlikePost, name="unlikePost"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import feed.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feed.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/user/urls.py
from . import views
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', authentication_views.LoginView.as_view(template_name='user/login.html'), name="login"),
    path('logout/', authentication_views.LogoutView.as_view(template_name='user/logout.html'), name="logout"),
    path('profile/<username>', views.profilepage, name="profile"),
    path('editProfile/<username>', views.editProfile, name="editProfile"),
    path('followProfile/<profile_id>', views.followProfile, name="followProfile"),
    path('unfollowProfile/<profile_id>', views.unfollowProfile, name="unfollowProfile"),
    path('deleteUser/<username>', views.deleteUser, name="deleteUser"),
    path('savedPosts/<username>', views.savedPosts, name="savedPosts"),
    path('likedPosts/<username>', views.likedPosts, name="likedPosts"),
    path('followingPosts/<username>', views.followingPosts, name="followingPosts"),
    path('followers/<username>', views.followers, name="followers"),
]

mysite/user/models.py
from django.db import models
from django.contrib.auth.models import User
import pytz

# Create your models here.
class Profile(models.Model):
    def __str__(self):
        return self.user.username

    UNITED_STATES_TIMEZONES = (
        ('US/Hawaii', 'Hawaii Standard Time'),
        ('US/Alaska', 'Alaska Standard Time'),
        ('US/Pacific', 'Pacific Standard Time'),
        ('US/Mountain', 'Mountain Standard Time'),
        ('US/Central', 'Central Standard Time'),
        ('US/Eastern', 'Eastern Standard Time')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=1000, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    timezone = models.CharField(max_length=50, choices=UNITED_STATES_TIMEZONES, default='US/Mountain')
    birthday = models.DateField(blank=True, null=True)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    banner = models.ImageField(default='profilebanner.jpg', upload_to='profile_banners')
    savedPosts = models.ManyToManyField('feed.Post', related_name='savedPosts')
    likedPosts = models.ManyToManyField('feed.Post', related_name='likedPosts')
    following = models.ManyToManyField('self', related_name='following')
    followers = models.ManyToManyField('self', related_name='followers')

mysite/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'location', 'timezone', 'birthday', 'image', 'banner']

mysite/user/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm, UpdateProfileForm
from .models import User, Profile
from feed.models import Post
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            return redirect('user:login')
    else:
        form = RegistrationForm()
    return render(request, 'user/register.html', {'form': form})

@login_required
def profilepage(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    post_list = Post.objects.filter(user=user).order_by('-id')

    post_search = request.GET.get('post_content')
    if post_search != '' and post_search is not None:
        post_list = post_list.filter(Q(title__icontains=post_search) | Q(content__icontains=post_search))

    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)

    title = "Posts:"
    mode = 'profile'

    return render(request, 'user/profile.html', {'profile': profile, 'post_list': post_list, 'title': title, 'mode': mode})

@login_required
def savedPosts(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    post_list = profile.savedPosts.all().order_by('-id')

    post_search = request.GET.get('post_content')
    if post_search != '' and post_search is not None:
        post_list = post_list.filter(Q(title__icontains=post_search) | Q(content__icontains=post_search))

    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)

    title = "Saved Posts:"
    mode = 'savedPosts'

    return render(request, 'user/profile.html', {'profile': profile, 'post_list': post_list, 'title': title, 'mode': mode})

@login_required
def likedPosts(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    post_list = profile.likedPosts.all().order_by('-id')

    post_search = request.GET.get('post_content')
    if post_search != '' and post_search is not None:
        post_list = post_list.filter(Q(title__icontains=post_search) | Q(content__icontains=post_search))

    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)

    title = "Liked Posts:"
    mode = 'likedPosts'

    return render(request, 'user/profile.html', {'profile': profile, 'post_list': post_list, 'title': title, 'mode': mode})

@login_required
def followingPosts(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    following_list = profile.following.all()

    post_id_list = set()
    for following in following_list:
        for post in Post.objects.filter(user=following.user):
            post_id_list.add(post.id)

    post_list = Post.objects.filter(pk__in=post_id_list).order_by('-id')

    post_search = request.GET.get('post_content')
    if post_search != '' and post_search is not None:
        post_list = post_list.filter(Q(title__icontains=post_search) | Q(content__icontains=post_search))

    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)

    title = "Followed Accounts' Posts:"
    mode = 'followingPosts'

    return render(request, 'user/profile.html', {'profile': profile, 'post_list': post_list, 'title': title, 'mode': mode})

@login_required
def followers(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    follower_list = profile.followers.all()

    return render(request, 'user/followers.html', {'profile': profile, 'follower_list': follower_list})

@login_required
def editProfile(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    form = UpdateProfileForm(request.POST or None, request.FILES or None, instance=profile)

    if form.is_valid():
        form.save()
        return redirect(request.GET.get('next'))

    return render(request, 'user/editProfile.html', {'form': form, 'profile': profile})

class UpdateProfile(UpdateView):
    model = Profile
    fields = ['bio', 'image']
    template_name = 'user/editProfile.html'
    success_url = reverse_lazy('feed:feed')

@login_required
def followProfile(request, profile_id):
    profileToFollow = Profile.objects.get(id=profile_id)
    profileFollowing = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        profileFollowing.following.add(profileToFollow)
        profileToFollow.followers.add(profileFollowing)
        return redirect(request.GET.get('next'))

    return render(request, 'user/followProfile.html', {'profileToFollow': profileToFollow, 'profileFollowing': profileFollowing})

@login_required
def unfollowProfile(request, profile_id):
    profileToFollow = Profile.objects.get(id=profile_id)
    profileFollowing = Profile.objects.get(user=request.user)

    if request.method == 'POST':
        profileFollowing.following.remove(profileToFollow)
        profileToFollow.followers.remove(profileFollowing)
        return redirect(request.GET.get('next'))

    return render(request, 'user/unfollowProfile.html', {'profileToFollow': profileToFollow, 'profileFollowing': profileFollowing})

@login_required
def deleteUser(request, username):
    user = User.objects.get(username=username)

    if request.method == 'POST':
        user.delete()
        return redirect('feed:index')

    return render(request, 'user/deleteUser.html', {'user': user})

mysite/user/templates/user/deleteUser.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-2">
            <form method="POST">
                {% csrf_token %}
                <h2>Are you sure you want to delete '{{ user.username }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

mysite/user/templates/user/editProfile.html
{% extends 'feed/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            Edit Profile
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name|title }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn-info">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/user/templates/user/followProfile.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-5">
            <form method="POST">
                {% csrf_token %}
                <h2>Follow '{{ profileToFollow.user.username }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}

mysite/user/templates/user/followers.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-3 offset-md-1">
            <a href="{% url 'user:profile' profile.user.username %}" class="btn btn-info" style="margin-left: 20px;">< Back to {{ profile.user.username }}'s Profile</a>
        </div>
        <div class="col-md-6">
            <h1>{{ profile.user.username }}'s Followers:</h1>
        </div>
    </div>
    <hr>
    {% for follower in follower_list %}
        <div class="row">
            <div class="col-md-8 offset-md-4">
                <a href="{% url 'user:profile' follower %}">
                    <div class="row">
                        <img src="{{ follower.image.url }}" height="50px" style="margin-right: 5px; margin-left: 20px;">
                        <h2>{{ follower.user.username }}</h2>
                    </div>
                </a>
            </div>
        </div>
        <br>
    {% endfor %}
{% endblock %}

mysite/user/templates/user/login.html
{% extends 'feed/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name|title }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn btn-info">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/user/templates/user/logout.html
{% extends 'feed/base.html' %}

{% block body %}
    <br><br>
    <div class="row">
        <div class="col-md-6 offset-md-4">
            <h1>You have been logged out!</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 offset-md-5">
            <a href="{% url 'user:login' %}">
                <h3>Back to login</h3>
            </a>
        </div>
    </div>
{% endblock %}

mysite/user/templates/user/profile.html
{% extends 'feed/base.html' %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <img src="{{ profile.banner.url }}" width="100%" height="200px" style="overflow: hidden; object-fit: cover;">
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-3 offset-md-1">
            <img src="{{ profile.image.url }}" width="100%" />
        </div>
        <div class="col-md-6">
            <h1>{{ profile.user.username }}</h1>
            <h4>Followers:
                <a href="{% url 'user:followers' profile.user.username %}?next={{ request.path }}">{{ profile.followers.all.count }}</a>
            </h4>
            <h5>{{ profile.birthday }}</h5>
            <h5>{{ profile.location }}</h5>
            <h4>{{ profile.bio }}</h4>
        </div>
        <div class="col-md-2">
            {% if profile.user != request.user %}
                {% if profile not in request.user.profile.following.all %}
                    <a href="{% url 'user:followProfile' profile.id %}?next={{ request.path }}" class="btn btn-success" style="margin-bottom: 5px;">Follow</a>
                {% endif %}
                {% if profile in request.user.profile.following.all %}
                    <a href="{% url 'user:unfollowProfile' profile.id %}?next={{ request.path }}" class="btn btn-secondary" style="margin-bottom: 5px;">Unfollow</a>
                {% endif %}
                <a href="#" class="btn btn-primary" style="margin-bottom: 5px;">Message</a>
            {% endif %}
            {% if profile.user == request.user %}
                <a href="{% url 'user:editProfile' profile.user.username %}?next={{ request.path }}" class="btn btn-warning">Edit Profile</a>
                <a href="{% url 'user:deleteUser' profile.user.username %}" class="btn btn-danger btn-sm">Delete Account</a>
            {% endif %}
        </div>
    </div>
    <br>
    <nav class="navbar navbar-dark bg-dark">
        <div class="navbar">
            <a href="{% url 'user:profile' profile.user.username %}" class="nav-item nav-link text-light">Posts</a>
            <a href="{% url 'user:likedPosts' profile.user.username %}" class="nav-item nav-link text-light">Likes</a>
            {% if profile.user == request.user %}
                <a href="{% url 'user:followingPosts' profile.user.username %}" class="nav-item nav-link text-light">Following</a>
                <a href="{% url 'user:savedPosts' profile.user.username %}" class="nav-item nav-link text-light">Saved Posts</a>
            {% endif %}
        </div>
    </nav>
    <br>
    <div class="row">
        <div class="col-md-4 offset-md-1">
            <h2>{{ title }}</h2>
        </div>
        <div class="col-md-3 offset-md-4">
            <form action="" method="GET">
                <input type="search" name="post_content" value="{{ request.GET.post_content }}">
                <button type="submit" class="btn btn-secondary btn-sm">Search</button>
            </form>
            {% if mode == 'profile' %}
                <div class="offset-md-2">
                    <a href="{% url 'user:profile' profile.user.username %}" class="btn btn-secondary btn-sm">Clear Search</a>
                </div>
            {% endif %}
            {% if mode == 'followingPosts' %}
                <div class="offset-md-2">
                    <a href="{% url 'user:followingPosts' profile.user.username %}" class="btn btn-secondary btn-sm">Clear Search</a>
                </div>
            {% endif %}
            {% if mode == 'likedPosts' %}
                <div class="offset-md-2">
                    <a href="{% url 'user:likedPosts' profile.user.username %}" class="btn btn-secondary btn-sm">Clear Search</a>
                </div>
            {% endif %}
            {% if mode == 'savedPosts' %}
                <div class="offset-md-2">
                    <a href="{% url 'user:savedPosts' profile.user.username %}" class="btn btn-secondary btn-sm">Clear Search</a>
                </div>
            {% endif %}
        </div>
    </div>
    {% for post in post_list %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <a href="{% url 'feed:postDetail' post.id %}">
                    <h2>{{ post.title }}</h2>
                </a>
                <a href="{% url 'user:profile' post.user.username %}">
                    <div class="col-md-4">
                        <div class="row">
                            <img src="{{ post.user.profile.image.url }}" height="30px" style="margin-right:5px;" />
                            <h6>{{ post.user.username }}</h6>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2">
                <a href="{% url 'feed:postDetail' post.id %}">
                    <img class="card" width="200px" src="{{ post.image.url }}" />
                </a>
            </div>
            <div class="col-md-4">
                <h4>{{ post.content|truncatewords_html:50 }}</h4>
            </div>
            <div class="col-md-2 offset-md-1">
                <a href="{% url 'feed:postDetail' post.id %}" class="btn btn-primary">Expand</a>
                {% if request.user.profile not in post.likes.all %}
                    <a href="{% url 'feed:likePost' post.id %}?next={{ request.path }}" class="btn btn-success btn-sm">Like Post</a>
                {% endif %}
                {% if request.user.profile in post.likes.all %}
                    <a href="{% url 'feed:unlikePost' post.id %}?next={{ request.path }}" class="btn btn-secondary btn-sm">Unlike Post</a>
                {% endif %}
                {% if post not in request.user.profile.savedPosts.all  %}
                    <a href="{% url 'feed:savePost' post.id %}?next={{ request.path }}" class="btn btn-info btn-sm">Save Post</a>
                {% endif %}
                {% if post in request.user.profile.savedPosts.all %}
                    <a href="{% url 'feed:unsavePost' post.id %}?next={{ request.path }}" class="btn btn-secondary btn-sm">Unsave Post</a>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 offset-md-2">
                {% load tz %}
                {% timezone request.user.profile.timezone %}
                <h6>{{ post.datetime }}</h6>
                {% endtimezone %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-2">
                <h6>Likes: {{ post.likes.count }}</h6>
            </div>
        </div>
        <hr>
    {% endfor %}
    <div class="row">
        <div class="col-md-4 offset-md-5">
            {% if post_list.has_previous %}
                <a href="?page=1{% if request.GET.post_content is not None %}&post_content={{ request.GET.post_content }}{% endif %}" class="btn btn-info">First</a>
                <a href="?page={{ post_list.previous_page_number }}{% if request.GET.post_content is not None %}&post_content={{ request.GET.post_content }}{% endif %}" class="btn btn-info">Previous</a>
            {% endif %}
            Page: {{ post_list.number }} of {{ post_list.paginator.num_pages }}
            {% if post_list.has_next %}
                <a href="?page={{ post_list.next_page_number }}{% if request.GET.post_content is not None %}&post_content={{ request.GET.post_content }}{% endif %}" class="btn btn-info">Next</a>
                <a href="?page={{ post_list.paginator.num_pages }}{% if request.GET.post_content is not None %}&post_content={{ request.GET.post_content }}{% endif %}" class="btn btn-info">Last</a>
            {% endif %}
        </div>
    </div>
    <br>
{% endblock %}

mysite/user/templates/user/register.html
{% extends 'feed/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            New User
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name|title }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn-info">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/user/templates/user/unfollowProfile.html
{% extends 'feed/base.html' %}

{% block body %}
    <br>
    <div class="row">
        <div class="col-md-10 offset-md-5">
            <form method="POST">
                {% csrf_token %}
                <h2>Unfollow '{{ profileToFollow.user.username }}'?</h2>
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}